@@ -9,42 +9,85 @@ theme: jekyll-theme-chirpy
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Paris

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Felipe Carrau Stewart # the main title

tagline: Firmware Engineer # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  This is my tech blog and diary.

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://fcarraustewart.github.io"

github:
  username: fcarraustewart # change to your GitHub username

twitter:
  username: CarrauFeli45389 # change to your Twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Felipe Carrau Stewart
  email: carraufelipe@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.linkedin.com/in/carraufelipe # change to your Twitter homepage
    - https://github.com/fcarraustewart # change to your GitHub homepage
    - https://sites.google.com/view/carraufelipe
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username













































theme_mode: # [light | dark]

# The CDN endpoint for media resources.
@@ -52,10 +95,10 @@ theme_mode: # [light | dark]
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn: "https://chirpy-img.netlify.app"

# the avatar on sidebar, support local or CORS resources
avatar: https://avatars.githubusercontent.com/u/39782345?s=96&v=4

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
