/*
 * Binacle — the navigation graph for /binacle/.
 *
 * Renders an Obsidian-style force-directed graph of tech stacks (tags),
 * areas (categories) and dev-blog posts. Data comes from the build-time
 * /binacle/graph-data.json (generated by _plugins/binacle-graph.rb).
 *
 * Requires the `ForceGraph` UMD global (loaded from CDN in _tabs/binacle.html).
 * Click a post node to open the post; click a stack/area node to focus its
 * neighbourhood. No build step, no bundler — plain script.
 */
(function () {
  var el = document.getElementById("binacle-graph");
  if (!el) return;
  if (typeof ForceGraph === "undefined") {
    el.innerHTML =
      '<p style="padding:1rem">Graph library failed to load (offline?).</p>';
    return;
  }

  // Colours tuned for both Chirpy light & dark themes.
  var COLOR = { post: "#7b6cf6", category: "#e5534b", tag: "#3aa0ff" };
  var src = el.getAttribute("data-src") || "/binacle/graph-data.json";

  fetch(src)
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (data) {
      // Adjacency for neighbour-highlighting on hover/click.
      var adj = {};
      (data.links || []).forEach(function (l) {
        (adj[l.source] = adj[l.source] || []).push(l.target);
        (adj[l.target] = adj[l.target] || []).push(l.source);
      });

      var highlight = null; // id of focused node, or null

      function isLit(id) {
        return (
          !highlight ||
          id === highlight ||
          (adj[highlight] && adj[highlight].indexOf(id) !== -1)
        );
      }

      function sizeOf(n) {
        if (n.kind === "post") return 4;
        return 4 + Math.min(8, (n.count || 1) * 1.6); // hubs grow with degree
      }

      var graph = ForceGraph()(el)
        .width(el.clientWidth)
        .height(el.clientHeight)
        .backgroundColor("rgba(0,0,0,0)")
        .nodeId("id")
        .nodeRelSize(4)
        .nodeVal(sizeOf)
        .linkColor(function () {
          return "rgba(128,128,128,0.25)";
        })
        .linkWidth(function (l) {
          var s = typeof l.source === "object" ? l.source.id : l.source;
          var t = typeof l.target === "object" ? l.target.id : l.target;
          return highlight && (isLit(s) && isLit(t)) ? 1.5 : 0.5;
        })
        .nodeCanvasObject(function (node, ctx, scale) {
          var r = sizeOf(node);
          var lit = isLit(node.id);
          ctx.globalAlpha = lit ? 1 : 0.15;

          ctx.beginPath();
          ctx.arc(node.x, node.y, r, 0, 2 * Math.PI);
          ctx.fillStyle = COLOR[node.kind] || "#999";
          ctx.fill();

          // label posts always; stacks/areas when zoomed-in or focused
          var showLabel = node.kind !== "post" || scale > 2.5 || node.id === highlight;
          if (showLabel) {
            var fontSize = Math.max(3, 11 / scale);
            ctx.font = fontSize + "px sans-serif";
            ctx.textAlign = "center";
            ctx.textBaseline = "top";
            ctx.fillStyle = getComputedStyle(document.documentElement)
              .getPropertyValue("--text-color") || "#888";
            ctx.fillText(node.label, node.x, node.y + r + 1);
          }
          ctx.globalAlpha = 1;
        })
        .onNodeHover(function (node) {
          el.style.cursor = node ? "pointer" : "default";
        })
        .onNodeClick(function (node) {
          if (node.kind === "post" && node.url) {
            window.location.href = node.url;
            return;
          }
          // focus/unfocus a stack or area
          highlight = highlight === node.id ? null : node.id;
          graph.nodeColor(graph.nodeColor()); // nudge a re-render
        });

      // keep the canvas sized to its container
      window.addEventListener("resize", function () {
        graph.width(el.clientWidth).height(el.clientHeight);
      });
    })
    .catch(function (err) {
      el.innerHTML =
        '<p style="padding:1rem">Could not load graph data: ' +
        err.message +
        "</p>";
    });
})();
